version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
      - /app/node_modules
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=B^dg#t
      - MYSQL_DATABASE=budget
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:8.0
    volumes:
      - redis_data:/data
volumes:
  mysql_data:
  redis_data:
